name: Integration tests

on:
  push:
    branches-ignore:
      - master

env:
  NODE_VERSION: 20

jobs:
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/composites/node_setup

      - name: Start Integration tests
        run: npm run test:integration
