name: Release

on:
  # On push to master branch and only if the package.json has changed
  push:
    paths:
      - package.json
    branches:
      - master

env:
  NODE_VERSION: 20
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  release:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Run Unit tests
        run: npm run test:unit

      - name: Run Integration tests
        run: npm run test:integration

      - name: Build
        run: npm run build

      - name: Get version from package.json
        run: echo "VERSION=$(jq -r .version < package.json)" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ env.NPM_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ env.NPM_AUTH_TOKEN }}
